language: generic
sudo: false
cache: apt

os:
  - linux
  - osx

env:
  global: LANGUAGE=C++
  matrix:
    - BUILD_COMMAND="./build.sh"
    - BUILD_COMMAND="./build_lookup.sh"

addons:
  apt:
    packages:
      - g++-5
      - libboost-all-dev
      - libleveldb-dev
      - libjsoncpp-dev
      - libsnappy-dev
    sources: &sources
      - r-packages-trusty
      - llvm-toolchain-trusty
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pkg-config jsoncpp leveldb; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-5 CC=gcc-5; fi

script:
  - (eval "$BUILD_COMMAND")
  - ctest
